# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: python-koji-fedoramessaging-messages.spec

# add or remove files that should be synced
files_to_sync:
  - python-koji-fedoramessaging-messages.spec
  - .packit.yaml

# name in upstream package repository/registry (e.g. in PyPI)
upstream_package_name: koji-fedoramessaging-messages
# downstream (Fedora) RPM package name
downstream_package_name: python-koji-fedoramessaging-messages
upstream_tag_template: v{version}

# dependencies needed to prepare for and build the source RPM
srpm_build_deps:
  - poetry

actions:
  post-upstream-clone:
    - "./make-spec.sh"
  create-archive:
    # Since version 1.2.2, Poetry adheres to https://peps.python.org/pep-0625/
    # (underscores over dashes)
    - "poetry build -q -n -f sdist"
    - "sh -c 'echo dist/koji_fedoramessaging_messages-$(poetry version -s).tar.gz'"
  get-current-version:
    - "poetry version -s"

targets:
  - fedora-latest-stable

jobs:

  # upon PRs, perform COPR builds
  - job: copr_build
    trigger: pull_request

  # upon upstream releases, perform COPR builds
  - job: copr_build
    trigger: release
